targets:
  $default:
    builders:
      list_gen|mimetypeListBuilder:
        enabled: true
        options:
          build_extensions:
            '{{}}.mimetypeList.yaml': '{{}}.mimetypeList.dart'
        generate_for:
          - lib/**